# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_eventpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
