# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('project', '0003_auto_20190605_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
