# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190619_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
