# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20190707_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='eventpluginmodel',
            name='show_only_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
