# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_arrestee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventbrite_link',
            field=models.URLField(blank=True, help_text='Link to Eventbrite event URL', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Link to Facebook event URL', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='other_link',
            field=models.URLField(blank=True, help_text='Link to any other event page URL', null=True),
        ),
    ]
