# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('project', '0018_auto_20200118_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='project_calendarpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('limit', models.IntegerField(null=True))
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
