# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-15 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200304_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='article_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='email_address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='highlighted_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Article'),
        ),
        migrations.AddField(
            model_name='group',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='other_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='video_url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='group',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
