# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-15 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('project', '0021_auto_20200315_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
