# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-16 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
