# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_event_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpluginmodel',
            old_name='show_only_promoted',
            new_name='prioritise_promoted',
        ),
    ]
