# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200612_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.BooleanField(default=True, help_text='Display article image throughout the site in the random header'),
        ),
    ]
