# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_article_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anon_user_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending'), ('A', 'Approved')], default='D', max_length=1),
        ),
    ]
