# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 09:57
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Event = apps.get_model('project', 'Event')
    Event.objects.all().update(status='A')

def reverse_func(apps, schema_editor):
    Event = apps.get_model('project', 'Event')
    Event.objects.all().update(status='D')


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20200819_1018'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
